app/models.py
# encoding: utf-8
from datetime import datetime
from . import db


class FeedType:
    DEFAULT = 0x00
    ZNYS = 0x01
    CJDA = 0x02
    GXRY = 0x02
    RYGJ = 0x03
    CLGJ = 0x04
    GWRY = 0x05
    QBZT = 0x06
    XYZS = 0x07
    TXXX = 0x08
    ZCMP = 0x09
    FKZH = 0x0a
    JQTS = 0x0b


class Feedback(db.Model):
    __tablename__ = 'feedback'
    id = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.Integer, default=FeedType.DEFAULT)
    read_flag = db.Column(db.Boolean, default=False, index=True)
    content = db.Column(db.Text)
    appends = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, default=datetime.now)
    author_name = db.Column(db.String(46), default='AnonymousUser')
    author_id = db.Column(db.String(18))
    author_dept = db.Column(db.String(64))
    author_contact = db.Column(db.String(64))

app/__init__.py
# encoding: utf-8
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import Config

bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    Config.init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
# encoding: utf-8
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
# encoding: utf-8
import os
import uuid
from time import strftime
from flask import render_template, redirect, abort, url_for, flash, request, current_app, send_from_directory
from flask_wtf import Form
from wtforms import TextAreaField, FileField, SelectField, SubmitField, StringField  # , validators
from . import main
from .. import db
from ..models import Feedback


class FeedbackForm(Form):
    subject = SelectField(u'类型', coerce=int)
    content = TextAreaField(u'意见及建议')  # validators=[validators.Length(min=12, message=u'至少输入12个字符')]
    images = FileField(u'上传图片')
    submit = SubmitField(u'提交')
    author_name = StringField(u'姓名')
    author_id = StringField(u'身份证号')
    author_dept = StringField(u'部门')
    author_contact = StringField(u'联系方式')

    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        subjects_list = current_app.config['FEEDBACK_SUBJECTS']
        self.subject.choices = [(i, subjects_list[i]) for i in range(0, len(subjects_list))]


@main.route('/')
def index():
    return redirect(url_for('.add_feedback'))


@main.route('/feedback/', methods=['GET', 'POST'])
def add_feedback():
    form = FeedbackForm()
    if form.validate_on_submit():
        feedback = Feedback(subject=form.subject.data, content=form.content.data,
                            author_name=form.author_name.data, author_id=form.author_id.data,
                            author_dept=form.author_dept.data, author_contact=form.author_contact.data)
        appendix = u''
        file_list = request.files
        for i in file_list:
            img = file_list[i]
            if '.' in img.filename and img.filename.rsplit('.', 1)[1] in current_app.config['ALLOWED_EXTENSIONS']:
                folder = strftime("%Y-%m")
                filename = uuid.uuid1().hex + '.' + img.filename.rsplit('.', 1)[1]
                path = os.path.join(current_app.config['UPLOAD_FOLDER'], folder)
                if not os.path.exists(path):
                    os.makedirs(path)
                img.save(os.path.join(current_app.config['UPLOAD_FOLDER'], folder, filename))
                appendix = appendix + u'<img src="/uploads/' + os.path.join(folder, filename) + u'"/>'
        feedback.appends = appendix
        db.session.add(feedback)
        flash(u'反馈意见已提交，谢谢！')
        return render_template('post-success.html', name=feedback.author_name, id_number=feedback.author_id,
                               dept=feedback.author_dept, contact=feedback.author_contact)
    arg_values = request.args if request.method == 'GET' else request.values
    form.author_name.data = arg_values.get(u'name', type=unicode)
    form.author_id.data = arg_values.get(u'id_number', type=unicode)
    form.author_dept.data = arg_values.get(u'dept', type=unicode)
    form.author_contact.data = arg_values.get(u'contact', type=unicode)
    if form.author_name.data is None or form.author_id.data is None or \
            form.author_dept.data is None or form.author_contact.data is None:
        abort(403)
    else:
        admin = True if form.author_id.data in current_app.config['FEEDBACK_ADMIN_LIST'] else False
        return render_template('post-feedback.html', form=form, admin=admin)


@main.route('/uploads/<folder>/<filename>/')
def uploaded_file(folder, filename):
    return send_from_directory(current_app.config['UPLOAD_FOLDER'], os.path.join(folder, filename))


@main.route('/manage/')
def manage_index():
    return redirect(url_for('.manage_feedback'))


@main.route('/manage/feedback/')
def manage_feedback():
    page = request.args.get('page', 1, type=int)
    pagination = Feedback.query.order_by(Feedback.timestamp.desc()).paginate(
        page, per_page=current_app.config['FLASKY_FEEDBACKS_PER_PAGE'], error_out=False)
    for i in range(0, len(pagination.items)):
        pagination.items[i].time = pagination.items[i].timestamp.strftime('%Y-%m-%d %H:%M:%S')
    return render_template('manage-feedback.html', feedbacks=pagination.items, pagination=pagination,
                           subjects=current_app.config['FEEDBACK_SUBJECTS'])


@main.route('/manage/feedback/<int:id>/')
def feedback_detail(id):
    feedback = Feedback.query.get_or_404(id)
    feedback.time = feedback.timestamp.strftime('%Y-%m-%d %H:%M:%S')
    return render_template('feedback-detail.html', feedback=feedback,
                           subjects=current_app.config['FEEDBACK_SUBJECTS'])


@main.route('/manage/mark-solved/<int:id>/')
def mark_solved(id):
    feedback = Feedback.query.get_or_404(id)
    feedback.read_flag = True
    db.session.add(feedback)
    return 'success - mark solved'


@main.route('/manage/mark-unsolved/<int:id>/')
def mark_unsolved(id):
    feedback = Feedback.query.get_or_404(id)
    feedback.read_flag = False
    db.session.add(feedback)
    return 'success - mark unsolved'


@main.route('/manage/delete/<int:id>/')
def delete_feedback(id):
    feedback = Feedback.query.get_or_404(id)
    db.session.delete(feedback)
    return 'success - delete feedback'

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/base.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}江西省公安厅大数据实战应用平台 - 意见反馈系统{% endblock %}</title>
    <!-- Set render engine for 360 browser -->
    <meta name="renderer" content="webkit">
    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Amaze UI"/>
    <link rel="apple-touch-icon-precomposed" href="{{ url_for('static', filename='img/app-icon72x72@2x.png')}}">
    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="{{ url_for('static', filename='img/app-icon72x72@2x.png')}}">
    <meta name="msapplication-TileColor" content="#0e90d2">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/police.ico')}}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='img/police.ico')}}" type="image/x-icon">
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css')}}">
    {% endblock %}
    <!--[if lt IE 9]>
        <script src="{{ url_for('static', filename='js/html5shiv.min.js')}}"></script>
        <script src="{{ url_for('static', filename='js/respond.min.js')}}"></script>
    <![endif]-->
</head>
<body>
	<div class="nav-header">
		<div class="container">
			<img src="{{ url_for('static', filename='img/u01.png')}}" class="banner"/>
			<div class="clearfix"></div>
		</div>
	</div>
	<div class="main-wrapper subpage">
		<div class="container">
            {% block content %}{% endblock %}
		</div>
	</div>
    <div class="footer">
        <div class="container">
			<div style="padding-top:45px; text-align:center; font-size:1.4rem;">江西省公安厅&nbsp;&copy;&nbsp;2016&nbsp;版权所有<br>公安部第三研究所&nbsp;&nbsp;|&nbsp;&nbsp;技术支持：0791-6668956</div>
        </div>
    </div>
    {% block js %}
    <script src="{{ url_for('static', filename='js/jquery-3.1.1.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/common.js')}}"></script>
    {% endblock %}
</body>
</html>

app/templates/feedback-detail.html
{% extends 'base.html' %}

{% block title %}首页 | 江西公安大数据平台意见反馈系统{% endblock %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/feedback.css')}}">
{% endblock %}

{% block content %}
    <h1>关于：{{ subjects[feedback.subject] }}
        <a href="{{ url_for('.manage_feedback') }}" class="btn btn-primary btn-lg float-right" role="button">管理面板</a>
    </h1>
    <hr>

    <dl class="feed-info dl-horizontal">
        <dt>姓名：</dt>
        <dd>{{ feedback.author_name }}</dd>
        <dt>身份证号：</dt>
        <dd>{{ feedback.author_id }}</dd>
        <dt>所属部门：</dt>
        <dd>{{ feedback.author_dept }}</dd>
        <dt>联系方式：</dt>
        <dd>{{ feedback.author_contact }}</dd>
    </dl>

    <div class="feed-magnet">
        <div class="feed-title">
            <div class="subject">投递时间：{{ feedback.time }}</div>
            <div class="clearfix"></div>
        </div>
        <div class="feed-content">
            <p>{{ feedback.content }}</p>
            {{ feedback.appends|safe }}
        </div>
    </div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}首页 | 江西公安大数据平台意见反馈系统{% endblock %}

{% block content %}
    <h1>Index</h1>
{% endblock %}

app/templates/manage-feedback.html
{% extends 'base.html' %}
{% import "_macros.html" as macros %}

{% block title %}首页 | 江西公安大数据平台意见反馈系统{% endblock %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/feedback.css') }}"
          xmlns="http://www.w3.org/1999/html">
{% endblock %}

{% block content %}
    <h1>意见管理</h1>
    <hr>
    {% for feedback in feedbacks %}
    <div class="feed-magnet">
        <div class="feed-title">
            <div class="subject float-left">{{ subjects[feedback.subject] }}</div>
            <div class="info float-left">
                <span>用户：{{ feedback.author_name }}</span>
                <span>部门：{{ feedback.author_dept }}</span>
                <span>{{ feedback.time }}</span>
            </div>
            <button class="btn btn-danger float-right" onclick="_execute_url('{{ url_for(".delete_feedback", id=feedback.id) }}')">删除</button>
            <a class="btn btn-primary float-right" href="{{ url_for('.feedback_detail', id=feedback.id) }}">详情</a>
            {% if feedback.read_flag %}
                <button class="btn btn-success float-right" onclick="_execute_url('{{ url_for(".mark_unsolved", id=feedback.id) }}')">已处理</button>
            {% else %}
                <button class="btn btn-warning float-right" onclick="_execute_url('{{ url_for(".mark_solved", id=feedback.id) }}')">未处理</button>
            {% endif %}
            <div class="clearfix"></div>
        </div>
        <div class="feed-content">
            <p>{{ feedback.content }}</p>
            <div>{{ feedback.appends|safe }}</div>
        </div>
    </div>
    {% endfor %}

    {% if pagination %}
    <div class="pagination">
        {{ macros.pagination_widget(pagination, '.manage_feedback') }}
    </div>
    {% endif %}
{% endblock %}

{% block js %}
    {{ super() }}
    <script type="text/javascript">
        function _execute_url(url) {
            $.ajax({
                url : url,
                success:function() {
                    window.location.reload();
                },
                error: function () {
                    alert('操作失败！');
                }
            });
        }
    </script>
{% endblock %}

app/templates/post-feedback.html
{% extends 'base.html' %}

{% block title %}意见反馈 | 江西公安大数据平台意见反馈系统{% endblock %}

{% block content %}
    <h1>意见与建议
        <a href="{{ url_for('.manage_feedback') }}" class="btn btn-primary btn-lg float-right{% if not admin %} hidden{% endif %}" role="button">管理面板</a></h1>
    <hr>

    <form class="form-horizontal" action="{{ url_for('main.add_feedback') }}" method="post" enctype="multipart/form-data" role="form">
        {{ form.hidden_tag() }}

        {{ form.author_name(type="hidden") }}
        {{ form.author_id(type="hidden") }}
        {{ form.author_dept(type="hidden") }}
        {{ form.author_contact(type="hidden") }}

        <div class="form-group">
            <label for="feedback-type" class="col-sm-2 control-label">类型</label>
            <div class="col-sm-3">
                {{ form.subject(id="feedback-type", class="form-control") }}
            </div>
        </div>

        <div class="form-group">
            <label for="feedback-content" class="col-sm-2 control-label">意见及建议</label>
            <div class="col-sm-8">
                {{ form.content(id="feedback-content", class="form-control", rows="12", placeholder="说点什么吧......") }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">上传图片</label>
            <div class="col-sm-4" id="file-inputs">
                <input type="file" class="form-control" name="u0"/>
            </div>
            <button type="button" class="btn btn-warning" onclick="append_input();">添加</button>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                {{ form.submit(value="提交", class="btn btn-primary") }}
            </div>
        </div>
    </form>
{% endblock %}

{% block js %}
{{ super() }}
    <script type="text/javascript">
        var counter = 0;
        function append_input() {
            var input = '<input type="file" class="form-control" name="u';
            counter++;
            input = input + counter.toString() + '"/>';
            $('#file-inputs').append(input);
        }
    </script>
{% endblock %}

app/templates/post-success.html
{% extends 'base.html' %}

{% block title %}提交成功 | 江西公安大数据平台意见反馈系统{% endblock %}

{% block content %}
    <br><br>
    <div class="row">
        <div class="col-sm-4 col-sm-offset-1">
            <h1>提交成功，谢谢！</h1>
            <br>
            <span class="text-info">自动跳转（5秒） ...... </span>
            <button type="button" class="btn btn-default btn-sm" onclick="redirect();">立即跳转</button>
        </div>
        <form id="go-back-form" action="{{ url_for('.add_feedback') }}" method="POST">
            <input name="name" type="hidden" value="{{ name }}" />
            <input name="id_number" type="hidden" value="{{ id_number }}" />
            <input name="dept" type="hidden" value="{{ dept }}" />
            <input name="contact" type="hidden" value="{{ contact }}" />
        </form>
    </div>
{% endblock %}

{% block js %}
    {{ super() }}
    <script type="text/javascript">
        function redirect() {
            $("#go-back-form").submit();
        }
        setInterval(redirect, 5000);
    </script>
{% endblock %}

app/templates/success.html
{% extends 'base.html' %}

{% block title %}提交成功 | 江西公安大数据平台意见反馈系统{% endblock %}

{% block content %}
    <br><br>
    <div class="row">
        <div class="col-sm-4 col-sm-offset-1">
            <h1>{{ message }}</h1>
            <br>
            <span class="text-info">本页面将在 3 秒后自动关闭 ...... </span>
            <button type="button" class="btn btn-default btn-sm" onclick="close_window();">立即关闭</button>
        </div>
    </div>
{% endblock %}

{% block js %}
    {{ super() }}
    <script type="text/javascript">
        function close_window() { window.close(); }
        setInterval(close_window, 3000);
    </script>
{% endblock %}